name: Feature request
description: Any improvements or new features you'd like to see in the Cocktail-Manager?
title: "feat: "
labels: [ enhancement ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature! Please fill the form in English!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues and nothing seems to be related to my idea.
          required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe. What is your idea?
      description: A concise description of the problem or idea you are facing or the motivetion behind this feature request. Technical or "how this could look like in the app" suggestions please in the next field.
      placeholder: |
        My brilliant idea ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like. How should it look in the app?
      description: You´re welcome to describe how your idea could be solved in the app, where and with which effects.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else? (Additional Context)
      description: |
        Links? References? Anything that will help us to understand!
    validations:
      required: false
