name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: yarn install
      - run: yarn build
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY_USER: ${{ github.actor }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
